### ISSUE TITLE
does not display in s22 mac / catalina

### ISSUE THREAD

**Issue by heaversm** [sketchfab/c4d-plugin#18]
Running Cinema4D S22 in OSX Catalina - installed plugin to default plugins directory as well as specifying a custom search path, restarted, nothing displays in the Extensions menu, nor the extensions > plugin manager directory.

**Comment by loicSketchfab** [comment]
Hi @heaversm :wave:, although I might come late to the party...

Do you still use the version S22 / did not manage to login ?

If you updated to R23, you could try to give a go at the latest release available [here](https://github.com/sketchfab/c4d-plugin/releases/tag/1.4.0), which could hopefully fix your issue.

If you still use S22 and did not manage to activate the add-on, there might be information in the Python console (Extensions -> Console or Python console) about what's going wrong. Could you paste the content of this console here ?

If there's nothing, this would tend to make me think the install paths are wrong... 
* Do you have other plugins installed on your system ?
* If yes, could you tell me in which directory the plugin installed on your computer (not sure if there might be some issues on OSX with specific paths, or maybe the folder got extracted a level too deep in the folder hierarchy...) ?

Hope something in there will help you install the plugin :crossed_fingers:

**Comment by jamieirvin** [comment]
Hi, I am having exactly the same issue.  I have followed the installation instructions to the letter ( I believe) and the Sketchfab plugin doesn't show.  Oddly, it worked just fine prior to updating the OS to Catalina over xmas.  

I am using R21. 

Below is a copy of my Python console as suggested above:


Traceback (most recent call last):
  File "/Users/ji/Library/Preferences/Maxon/Maxon Cinema 4D R21 (copy)_DCA21CCA/plugins/Sketchfab/SketchfabPlugin.pyp", line 39, in <module>
from sketchfab.ui_importer import *
  File "/Users/ji/Library/Preferences/Maxon/Maxon Cinema 4D R21 (copy)_DCA21CCA/plugins/Sketchfab/sketchfab/ui_importer.py", line 33, in <module>
import ui_login
  File "/Users/ji/Library/Preferences/Maxon/Maxon Cinema 4D R21 (copy)_DCA21CCA/plugins/Sketchfab/sketchfab/ui_login.py", line 14, in <module>
from api    import SketchfabApi
  File "/Users/ji/Library/Preferences/Maxon/Maxon Cinema 4D R21 (copy)_DCA21CCA/plugins/Sketchfab/sketchfab/api.py", line 20, in <module>
from PIL import Image
  File "/Users/ji/Library/Preferences/Maxon/Maxon Cinema 4D R21 (copy)_DCA21CCA/plugins/Sketchfab/dependencies/PIL/Image.py", line 93, in <module>
from . import _imaging as core
ImportError:cannot import name _imaging
Traceback (most recent call last):
  File "/Users/ji/Infinite 3D Dropbox/Resources/Software/MAXON/C4D R21/Plugins/Sketchfab/SketchfabPlugin.pyp", line 39, in <module>
from sketchfab.ui_importer import *
  File "/Users/ji/Library/Preferences/Maxon/Maxon Cinema 4D R21 (copy)_DCA21CCA/plugins/Sketchfab/sketchfab/ui_importer.py", line 33, in <module>
import ui_login
  File "/Users/ji/Library/Preferences/Maxon/Maxon Cinema 4D R21 (copy)_DCA21CCA/plugins/Sketchfab/sketchfab/ui_login.py", line 14, in <module>
from api    import SketchfabApi
  File "/Users/ji/Library/Preferences/Maxon/Maxon Cinema 4D R21 (copy)_DCA21CCA/plugins/Sketchfab/sketchfab/api.py", line 20, in <module>
from PIL import Image
  File "/Users/ji/Library/Preferences/Maxon/Maxon Cinema 4D R21 (copy)_DCA21CCA/plugins/Sketchfab/dependencies/PIL/Image.py", line 93, in <module>
from . import _imaging as core
ImportError:cannot import name _imaging
>>> 

Any help would be much appreciated 
Jamie

**Comment by jamieirvin** [comment]
this could be part of the issue...? (see attached) “_imaging.so” cannot be opened because the developer cannot be verified.
![image](https://user-images.githubusercontent.com/77287526/104206275-3be12280-5427-11eb-8916-ece44419399b.png)

**Comment by loicSketchfab** [comment]
Hi @jamieirvin 👋 

Some changes in the [latest release](https://github.com/sketchfab/c4d-plugin/releases/latest) of our plugin were made to adress that.

However, those are meant for C4D R23, so it should not work in R21. My first advice for your case would of course be to update from R21 to R23.

But if you can't do that, I could advise you to try the following, _with no guarantee of success_ though:
* Download [this .zip archive](https://github.com/sketchfab/c4d-plugin/releases/download/1.4.0/sketchfab-osx-1.4.0.zip)
* Replace the folder "dependencies/PIL" from your current installation (should be /Users/ji/Library/Preferences/Maxon/Maxon Cinema 4D R21 (copy)_DCA21CCA/plugins/Sketchfab/sketchfab/dependencies/PIL) with the one in the archive.
* Restart and launch C4D.

Sadly, I'm not really sure how to help if this does not work (no personal access to a MAC and we won't provide updates for older versions of the plugin), sorry for that.

Hopefully this could still help you to fix the plugin, please let me know in both cases (and do not hesitate to share the copy of your Python console if it still does not work, this info is indeed helpful 👍 ).

Good luck Jamie !

**Comment by jamieirvin** [comment]
Hi @loicSketchfab 

I am currently using the latest release.  However, I believe it to be a permissions issue within the new OS.  I tried the plugin with C4D R20 and, as the image above, received a raft of error messages as C4D launched.  To each I clicked 'cancel' and then altered the permissions in System preferences as each popped up.  I had to do this about 5 times, relaunching C4D each time.  Eventually R20 launched without any errors and the plugin worked.  However, this was not the case for R21.  The plugin still doesn't show in R21.  For now at least, I have a workaround.  

So Catalina's efforts to protect us from malware are causing no end of headaches.  I can confirm that most of my plugins within C4D are receiving the same errors, so it's not exclusive to Sketchfab.  

I am yet to try your alternative solution with the archive, but will try that later today and let you know how it goes.  

Currently it's not possible to upgrade to R23.  I would need to do so for the whole team and I don't want that headache whilst we are all working remotely!

Thanks for your help and I'll keep the thread updated. 

Jamie

**Comment by GrapefruitSpaceship** [comment]
Same issue, it does not appear in the menu. S22, Big Sur osx

Python:

Traceback (most recent call last):
  File "/Applications/Maxon Cinema 4D R22/plugins/Sketchfab/SketchfabPlugin.pyp", line 39, in <module>
from sketchfab.ui_importer import *
  File "/Applications/Maxon Cinema 4D R22/plugins/Sketchfab/sketchfab/ui_importer.py", line 29, in <module>
from import_gltf import ImportGLTF
  File "/Applications/Maxon Cinema 4D R22/plugins/Sketchfab/sketchfab/import_gltf.py", line 28, in <module>
from gltfio.imp.gltf2_io_gltf import glTFImporter
  File "/Applications/Maxon Cinema 4D R22/plugins/Sketchfab/gltfio/__init__.py", line 15, in <module>
from .imp import *
  File "/Applications/Maxon Cinema 4D R22/plugins/Sketchfab/gltfio/imp/__init__.py", line 15, in <module>
from .gltf2_io_gltf import *
  File "/Applications/Maxon Cinema 4D R22/plugins/Sketchfab/gltfio/imp/gltf2_io_gltf.py", line 15, in <module>
from ..com.gltf2_io import gltf_from_dict
ImportError:No module named com.gltf2_io
Traceback (most recent call last):
  File "/Users/williamchamber/Library/Preferences/Maxon/Maxon Cinema 4D R22_F2A48324/plugins/sketchfab-osx-1.4.0/SketchfabPlugin.pyp", line 39, in <module>
from sketchfab.ui_importer import *
  File "/Applications/Maxon Cinema 4D R22/plugins/Sketchfab/sketchfab/ui_importer.py", line 29, in <module>
from import_gltf import ImportGLTF
  File "/Applications/Maxon Cinema 4D R22/plugins/Sketchfab/sketchfab/import_gltf.py", line 28, in <module>
from gltfio.imp.gltf2_io_gltf import glTFImporter
  File "/Users/williamchamber/Library/Preferences/Maxon/Maxon Cinema 4D R22_F2A48324/plugins/sketchfab-osx-1.4.0/gltfio/__init__.py", line 15, in <module>
from .imp import *
  File "/Users/williamchamber/Library/Preferences/Maxon/Maxon Cinema 4D R22_F2A48324/plugins/sketchfab-osx-1.4.0/gltfio/imp/__init__.py", line 15, in <module>
from .gltf2_io_gltf import *
  File "/Users/williamchamber/Library/Preferences/Maxon/Maxon Cinema 4D R22_F2A48324/plugins/sketchfab-osx-1.4.0/gltfio/imp/gltf2_io_gltf.py", line 15, in <module>
from ..com.gltf2_io import gltf_from_dict
ImportError:No module named com.gltf2_io
Traceback (most recent call last):
  File "/Users/williamchamber/NetApp Inc/DXD - Documents/Ricky/3D/C4D/Plugins/Sketchfab/SketchfabPlugin.pyp", line 39, in <module>
from sketchfab.ui_importer import *
  File "/Applications/Maxon Cinema 4D R22/plugins/Sketchfab/sketchfab/ui_importer.py", line 29, in <module>
from import_gltf import ImportGLTF
  File "/Applications/Maxon Cinema 4D R22/plugins/Sketchfab/sketchfab/import_gltf.py", line 28, in <module>
from gltfio.imp.gltf2_io_gltf import glTFImporter
  File "/Users/williamchamber/NetApp Inc/DXD - Documents/Ricky/3D/C4D/Plugins/Sketchfab/gltfio/__init__.py", line 15, in <module>
from .imp import *
  File "/Users/williamchamber/NetApp Inc/DXD - Documents/Ricky/3D/C4D/Plugins/Sketchfab/gltfio/imp/__init__.py", line 15, in <module>
from .gltf2_io_gltf import *
  File "/Users/williamchamber/NetApp Inc/DXD - Documents/Ricky/3D/C4D/Plugins/Sketchfab/gltfio/imp/gltf2_io_gltf.py", line 15, in <module>
from ..com.gltf2_io import gltf_from_dict
ImportError:No module named com.gltf2_io
>>> 

Thanks

-bil

**Comment by echoandzoey** [comment]
hello，i use R23 008 ,and i improt the plugins successfully, also i log in the account successfully,but when i download the model,it just came out that Download url request  error : i have no permission to perform this action.
